### ISSUE TITLE
QM_Collector_WPBP_Debug_Output already in use

### ISSUE THREAD

**Issue by jeff-preload** [WPBP/Debug#3]
Hi,
I've created 2 plugins on the same wordpress install using  wpbp-generator which includes this component.
When both plugins are active I get error:
`error: Cannot declare class QM_Collector_WPBP_Debug_Output, because the name is already in use in /[localpath]/wp-content/plugins/my-new-plugin/vendor/wpbp/debug/QM_Collector_WPBP_Debug_Output.php on line 0`

Perhaps class QM_Collector_WPBP_Debug_Output needs an
`if ( !class_exists( 'QM_Collector_WPBP_Debug_Output' ) )`
wrapped around it?

Modification tested ok with local version.

**Comment by Mte90** [comment]
The autoloader should handle that, it is not suggested that class autoload have a check for `class_exists`.
The other plugin how to include the library?

**Comment by jeff-preload** [comment]
Both plugins I'm working with are stock installs from  [wpbp-generator](https://github.com/WPBP/generator) with no other changes other than the name of the plugin.

Perhaps the autoloader is not used as QM_Collector_WPBP_Debug_Output.php is included in function 'load' on line 43 of debug.php

Which-ever plugin loads first, no problem.  The second plugin sees the duplicate object at the include.

**Comment by Mte90** [comment]
You are right, I have to improve the autoload of also the other files.
I will check asap and fix it!

**Comment by jeff-preload** [comment]
I'm new to composer, and autoload.  classmaps are still a bit of a mystery too.
Looking forward to seeing your solution. : )

**Comment by Mte90** [comment]
New version available with the fix :-)

**Comment by jeff-preload** [comment]
Cheers, works a treat!
