### ISSUE TITLE
log not showing in tab

### ISSUE THREAD

**Issue by mrqaidi** [WPBP/Debug#4]
Hi

looks like query debug made some changes to JavaScript  method to show tabs that has been clicked  . after  checking  i found out that    
`strtolower( str_replace( ' ', '_', $this->title ) );`

need to be changed with 
`strtolower( str_replace( ' ', '-', $this->title ) );` 

in all 3 php file files

**Comment by Mte90** [comment]
Thanks for the pr I am releasing a new version
